[project]
name = "dandihub-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dandi>=0.69.3",
    "jupyterlab>=4.4.5",
]
